image: maven:3.6.3-jdk-11-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: one-key-to-rule-them-all
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository/
    - ${CI_PROJECT_DIR}/target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
