image: openjdk:11-jdk

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - echo 'IMAGES';
      docker images -q;
      for container in $(docker ps -aq);
      do
          docker rm -f $container
      done

      for image in $(docker images -q);
      do
      docker rmi $image
      done
    - mvn compile

test:
  stage: test
  script:
    - mvn test
